# Generated by Django 5.1.5 on 2025-03-04 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('sales', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('discount', models.FloatField()),
                ('profit', models.IntegerField()),
            ],
        ),
    ]
